package af.shizuku.manager.utils

import android.content.Context
import org.json.JSONObject
import af.shizuku.manager.ShizukuSettings

object SettingsBackupManager {

    private const val VERSION_KEY = "_version"
    private const val BACKUP_VERSION = 1

    // Keys that are ephemeral, device-specific, or migration-state — must not cross device
    // boundaries. User-facing preference keys (theme, features, API keys) are NOT excluded.
    private val EXCLUDED_KEYS = setOf(
        // Remote DB cache
        ShizukuSettings.Keys.KEY_LAST_DB_UPDATE,
        ShizukuSettings.Keys.KEY_REMOTE_DB_JSON,
        ShizukuSettings.Keys.KEY_REMOTE_DB_ETAG,
        ShizukuSettings.Keys.KEY_REMOTE_DB_LAST_MODIFIED,
        // Update-check timestamps
        ShizukuSettings.Keys.KEY_LAST_UPDATE_CHECK,
        ShizukuSettings.Keys.KEY_LAST_CHECK_FAILED,
        // Migration / one-time flags — restoring these would skip migrations on new installs
        ShizukuSettings.Keys.KEY_MIGRATION_OFFERED,
        ShizukuSettings.Keys.KEY_HOME_NOTIF_PERMISSION_REQUESTED,
        ShizukuSettings.Keys.KEY_MIGRATED_APPCOMPAT_LOCALES,
        ShizukuSettings.Keys.KEY_LAST_SEEN_CHANGELOG_VERSION,
        ShizukuSettings.Keys.KEY_SYNCED_START_ON_BOOT_DEFAULT,
        // Ephemeral runtime state
        ShizukuSettings.Keys.KEY_SERVER_STARTED_BUILD,
        ShizukuSettings.Keys.KEY_LAST_SETTLED_STATE,
        // Internal Shizuku auth token — re-generated by the server on each start
        "auth_token",
        // Device-specific storage URI (path on destination device will differ)
        ShizukuSettings.Keys.KEY_EXPORT_DIR_URI,
    )

    fun export(@Suppress("UNUSED_PARAMETER") context: Context): String {
        // Use ShizukuSettings.getPreferences() — not context.getSharedPreferences() — because
        // ShizukuSettings.initialize() stores settings in device-protected storage
        // (createDeviceProtectedStorageContext()) on API 24+, which is a different file than the
        // credential-encrypted storage that plain getSharedPreferences() returns. Always use the
        // same SharedPreferences instance that the rest of the app reads and writes.
        val prefs = ShizukuSettings.getPreferences() ?: return "{}"
        val json = JSONObject()
        json.put(VERSION_KEY, BACKUP_VERSION)
        for ((key, value) in prefs.all) {
            if (key in EXCLUDED_KEYS) continue
            when (value) {
                is Boolean -> json.put(key, value)
                is Int -> json.put(key, value)
                is Long -> json.put(key, value)
                is Float -> json.put(key, value)
                is String -> json.put(key, value)
                is Set<*> -> json.put(key, org.json.JSONArray(value.toList()))
            }
        }
        return json.toString(2)
    }

    fun import(@Suppress("UNUSED_PARAMETER") context: Context, json: String): Boolean =
        importInternal(json, synchronous = false)

    /**
     * Like [import] but uses [SharedPreferences.Editor.commit] (synchronous disk write). Use this
     * from a [android.app.backup.BackupAgent] where the OS may start the app immediately after
     * the agent returns — [apply]'s async write could race with the first read on the new process.
     */
    fun importAndCommit(@Suppress("UNUSED_PARAMETER") context: Context, json: String): Boolean =
        importInternal(json, synchronous = true)

    private fun importInternal(json: String, synchronous: Boolean): Boolean {
        return try {
            val obj = JSONObject(json)
            val version = obj.optInt(VERSION_KEY, -1)
            if (version < 1) return false

            val prefs = ShizukuSettings.getPreferences() ?: return false
            val editor = prefs.edit()

            val keys = obj.keys()
            while (keys.hasNext()) {
                val key = keys.next()
                if (key == VERSION_KEY || key in EXCLUDED_KEYS) continue
                when (val v = obj.get(key)) {
                    is Boolean -> editor.putBoolean(key, v)
                    is Int -> editor.putInt(key, v)
                    is Long -> editor.putLong(key, v)
                    is Double -> editor.putFloat(key, v.toFloat())
                    is String -> editor.putString(key, v)
                    is org.json.JSONArray -> {
                        val set = (0 until v.length()).map { v.getString(it) }.toSet()
                        editor.putStringSet(key, set)
                    }
                }
            }
            if (synchronous) editor.commit() else { editor.apply(); true }
        } catch (e: Exception) {
            false
        }
    }
}
